/** 
 * 窗口ID枚举
 */
enum WindowID {
    /** 无效窗口 */
    Invalid = 0,

    /** 人物窗口 */
    RoleWindow = 1,
    /** 角色 */
    Role = 2,
    /** 背包 */
    Parcel = 3,
    /** 技能 */
    Skill = 4,
    /** 道具Tip */
    GoodsTip = 5,
    /** 装备Tip */
    EquipTip = 6,
    /** NPC任务对话界面 */
    NpcDoingTask = 7,
    /** 尊天炉窗口 */
    ZunTianLu = 8,
    /** 装备打造 */
    Forge = 9,
    /** 合成 */
    Synthesis = 10,
    /** 提示框 （确认、取消/确认） */
    PromptBox = 11,
    /** 活动窗口 */
    ActivityWindow = 12,
    /** 冒险 */
    MaoXian = 13,
    /** 战场 */
    ZhanChang = 14,
    /** 每日活跃 */
    MeiRiHuoYue = 15,
    /** 地图窗口 */
    Map = 16,
    /** 功能开启提示界面 */
    FunOpenTiShiPart = 17,
    /** 功能开启飞图标界面 */
    SystemOpenFlyPart = 18,
    /** 福利窗口 */
    WelfareWindow = 19,
    /** 七日登录 */
    SevenLogin = 20,
    /** 每日福利 */
    DailyWelfare = 21,
    /** 在线奖励 */
    OnlineReward = 22,
    /** 等级奖励 */
    GradeReward = 23,
    /** 潜心修炼 */
    MeditationReward = 24,
    /** 坐骑窗口 */
    ZuoQiWindow = 25,
    /** Vip界面 */
    Vip = 26,
    /** 商城窗口 */
    MallWindow = 27,
    /** 商城页签 */
    Mall = 28,
    /** 限时抢购 */
    MallBuyLimit = 29,
    /** 钻石商城 */
    MallDiamond = 30,
    /** 红钻商城 */
    MallBindingDiamond = 31,
    /** 银币商城 */
    MallSilver = 32,
    /** 首充 */
    FirstCharge = 33,
    /** NPC对话窗口 */
    NPCDialog = 34,
    /** 详细属性窗口 */
    PropertyWindow = 35,
    /** 属性加点窗口 */
    AttributePoint = 36,
    /** 充值福利 */
    ChargeWelfare = 37,
    /** 每日充值 */
    DayCharge = 38,
    /** 累计充值 */
    LeiJiCharge = 39,
    /** 累计消费 */
    LeiJiConsume = 40,
    /** 图腾 */
    Totem = 41,
    /** 虬龙图腾 */
    QiuLongTotem = 42,
    /** 蛟龙图腾 */
    JiaoLongTotem = 43,
    /** 螭龙图腾 */
    LiLongTotem = 44,
    /** 商人页签 */
    Business = 45,
    /** 斗气商人 */
    BusinessDouQi = 46,
    /** 帮会商人 */
    BusinessBangHui = 47,
    /** 寻龙商人 */
    BusinessXunLong = 48,
    /** 装备副本 */
    EquipFuBen = 49,
}